// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Vdom        from "bucklescript-tea/lib/es6/src/vdom.js";
import * as Tea_app     from "bucklescript-tea/lib/es6/src/tea_app.js";
import * as Tea_html    from "bucklescript-tea/lib/es6/src/tea_html.js";
import * as Pervasives  from "bs-platform/lib/es6/pervasives.js";
import * as Caml_format from "bs-platform/lib/es6/caml_format.js";

var init_model = /* record */[
  /* cur_val */0,
  /* cur_edit */0,
  /* disabled : false */0
];

function update(model, param) {
  if (typeof param === "number") {
    switch (param) {
      case 0 : 
          return /* record */[
                  /* cur_val */model[/* cur_val */0] + 1 | 0,
                  /* cur_edit */model[/* cur_edit */1],
                  /* disabled */model[/* disabled */2]
                ];
      case 1 : 
          return /* record */[
                  /* cur_val */model[/* cur_val */0] - 1 | 0,
                  /* cur_edit */model[/* cur_edit */1],
                  /* disabled */model[/* disabled */2]
                ];
      case 2 : 
          return init_model;
      case 3 : 
          return /* record */[
                  /* cur_val */model[/* cur_edit */1],
                  /* cur_edit */model[/* cur_edit */1],
                  /* disabled */model[/* disabled */2]
                ];
      case 4 : 
          return /* record */[
                  /* cur_val */model[/* cur_val */0],
                  /* cur_edit */model[/* cur_edit */1],
                  /* disabled : true */1
                ];
      
    }
  } else {
    return /* record */[
            /* cur_val */model[/* cur_val */0],
            /* cur_edit */param[0],
            /* disabled : false */0
          ];
  }
}

function view_button($staropt$star, title, msg) {
  var disabled = $staropt$star ? $staropt$star[0] : /* false */0;
  return Tea_html.button(/* None */0, /* None */0, /* :: */[
              Tea_html.onClick(msg),
              /* :: */[
                disabled ? Vdom.prop("disabled", "disabled") : Vdom.noProp,
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.text(title),
              /* [] */0
            ]);
}

function view(param) {
  var edit = function (input_val) {
    try {
      return /* Edit */[Caml_format.caml_int_of_string(input_val)];
    }
    catch (exn){
      return /* Disable */4;
    }
  };
  return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
              Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                    Tea_html.text(Pervasives.string_of_int(param[/* cur_val */0])),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                      view_button(/* None */0, "Increment", /* Increment */0),
                      /* [] */0
                    ]),
                /* :: */[
                  Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                        view_button(/* None */0, "Decrement", /* Decrement */1),
                        /* [] */0
                      ]),
                  /* :: */[
                    Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                          view_button(/* None */0, "Reset", /* Reset */2),
                          /* [] */0
                        ]),
                    /* :: */[
                      Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                            Tea_html.input$prime(/* None */0, /* None */0, /* :: */[
                                  Tea_html.onChange(/* None */0, edit),
                                  /* :: */[
                                    Tea_html.value(Pervasives.string_of_int(param[/* cur_edit */1])),
                                    /* [] */0
                                  ]
                                ], /* [] */0),
                            /* [] */0
                          ]),
                      /* :: */[
                        Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                              view_button(/* Some */[param[/* disabled */2]], "Set", /* Set */3),
                              /* [] */0
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var partial_arg = /* record */[
  /* model */init_model,
  /* update */update,
  /* view */view
];

function main(param, param$1) {
  return Tea_app.beginnerProgram(partial_arg, param, param$1);
}

export {
  init_model  ,
  update      ,
  view_button ,
  view        ,
  main        ,
  
}
/* No side effect */
