// Generated by BUCKLESCRIPT VERSION 1.7.4, PLEASE EDIT WITH CARE
'use strict';

import * as Vdom        from "bucklescript-tea/lib/es6/src/vdom.js";
import * as Block       from "bs-platform/lib/es6/block.js";
import * as Tea_app     from "bucklescript-tea/lib/es6/src/tea_app.js";
import * as Tea_html    from "bucklescript-tea/lib/es6/src/tea_html.js";
import * as Pervasives  from "bs-platform/lib/es6/pervasives.js";
import * as Caml_format from "bs-platform/lib/es6/caml_format.js";

var init_model = /* tuple */[
  0,
  0,
  /* false */0
];

function update(param, param$1) {
  var disable = param[2];
  var cur_edit = param[1];
  var cur_val = param[0];
  if (typeof param$1 === "number") {
    switch (param$1) {
      case 0 : 
          return /* tuple */[
                  cur_val + 1 | 0,
                  cur_edit,
                  disable
                ];
      case 1 : 
          return /* tuple */[
                  cur_val - 1 | 0,
                  cur_edit,
                  disable
                ];
      case 2 : 
          return init_model;
      case 3 : 
          return /* tuple */[
                  cur_edit,
                  cur_edit,
                  disable
                ];
      
    }
  } else if (param$1.tag) {
    return /* tuple */[
            cur_val,
            cur_edit,
            param$1[0]
          ];
  } else {
    return /* tuple */[
            cur_val,
            param$1[0],
            /* false */0
          ];
  }
}

function view_button($staropt$star, title, msg) {
  var disabled = $staropt$star ? $staropt$star[0] : /* false */0;
  return Tea_html.button(/* None */0, /* None */0, /* :: */[
              Tea_html.onClick(msg),
              /* :: */[
                disabled ? Vdom.prop("disabled", "disabled") : Vdom.noProp,
                /* [] */0
              ]
            ], /* :: */[
              Tea_html.text(title),
              /* [] */0
            ]);
}

function view(param) {
  var edit = function (input_val) {
    try {
      return /* Edit */Block.__(0, [Caml_format.caml_int_of_string(input_val)]);
    }
    catch (exn){
      return /* Disable */Block.__(1, [/* true */1]);
    }
  };
  return Tea_html.div(/* None */0, /* None */0, /* [] */0, /* :: */[
              Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                    Tea_html.text(Pervasives.string_of_int(param[0])),
                    /* [] */0
                  ]),
              /* :: */[
                Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                      view_button(/* None */0, "Increment", /* Increment */0),
                      /* [] */0
                    ]),
                /* :: */[
                  Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                        view_button(/* None */0, "Decrement", /* Decrement */1),
                        /* [] */0
                      ]),
                  /* :: */[
                    Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                          view_button(/* None */0, "Reset", /* Reset */2),
                          /* [] */0
                        ]),
                    /* :: */[
                      Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                            Tea_html.input$prime(/* None */0, /* None */0, /* :: */[
                                  Tea_html.onChange(/* None */0, edit),
                                  /* :: */[
                                    Tea_html.value(Pervasives.string_of_int(param[1])),
                                    /* [] */0
                                  ]
                                ], /* [] */0),
                            /* [] */0
                          ]),
                      /* :: */[
                        Tea_html.p(/* None */0, /* None */0, /* [] */0, /* :: */[
                              view_button(/* Some */[param[2]], "Set", /* Set */3),
                              /* [] */0
                            ]),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]);
}

var partial_arg = /* record */[
  /* model */init_model,
  /* update */update,
  /* view */view
];

function main(param, param$1) {
  return Tea_app.beginnerProgram(partial_arg, param, param$1);
}

export {
  init_model  ,
  update      ,
  view_button ,
  view        ,
  main        ,
  
}
/* No side effect */
